// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories.EFCore;

#nullable disable

namespace TarifDostuApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EstimatedUnitPrice")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedUnitPrice = 0.5,
                            IsCustom = false,
                            Name = "Tomato",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 2,
                            EstimatedUnitPrice = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Onion",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 3,
                            EstimatedUnitPrice = 9.9900000000000002,
                            IsCustom = false,
                            Name = "Chicken Breast",
                            Type = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 4,
                            EstimatedUnitPrice = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Egg",
                            Type = 2,
                            Unit = 0
                        },
                        new
                        {
                            Id = 5,
                            EstimatedUnitPrice = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Garlic",
                            Type = 0,
                            Unit = 3
                        },
                        new
                        {
                            Id = 6,
                            EstimatedUnitPrice = 0.14999999999999999,
                            IsCustom = false,
                            Name = "Olive Oil",
                            Type = 3,
                            Unit = 2
                        },
                        new
                        {
                            Id = 7,
                            EstimatedUnitPrice = 0.75,
                            IsCustom = false,
                            Name = "Red Pepper",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 8,
                            EstimatedUnitPrice = 0.050000000000000003,
                            IsCustom = false,
                            Name = "Rice",
                            Type = 4,
                            Unit = 1
                        },
                        new
                        {
                            Id = 9,
                            EstimatedUnitPrice = 8.5,
                            IsCustom = false,
                            Name = "Chicken Leg",
                            Type = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 10,
                            EstimatedUnitPrice = 0.5,
                            IsCustom = false,
                            Name = "Parsley",
                            Type = 0,
                            Unit = 4
                        },
                        new
                        {
                            Id = 11,
                            EstimatedUnitPrice = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Lentils",
                            Type = 5,
                            Unit = 1
                        },
                        new
                        {
                            Id = 12,
                            EstimatedUnitPrice = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Cheddar Cheese",
                            Type = 6,
                            Unit = 1
                        },
                        new
                        {
                            Id = 13,
                            EstimatedUnitPrice = 10.99,
                            IsCustom = false,
                            Name = "Ground Beef",
                            Type = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 14,
                            EstimatedUnitPrice = 0.25,
                            IsCustom = false,
                            Name = "Potato",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 15,
                            EstimatedUnitPrice = 0.029999999999999999,
                            IsCustom = false,
                            Name = "Flour",
                            Type = 9,
                            Unit = 1
                        },
                        new
                        {
                            Id = 16,
                            EstimatedUnitPrice = 0.14999999999999999,
                            IsCustom = false,
                            Name = "Yogurt",
                            Type = 6,
                            Unit = 1
                        },
                        new
                        {
                            Id = 17,
                            EstimatedUnitPrice = 0.5,
                            IsCustom = false,
                            Name = "Lemon",
                            Type = 7,
                            Unit = 0
                        },
                        new
                        {
                            Id = 18,
                            EstimatedUnitPrice = 1.0,
                            IsCustom = false,
                            Name = "Broccoli",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 19,
                            EstimatedUnitPrice = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Milk",
                            Type = 6,
                            Unit = 2
                        },
                        new
                        {
                            Id = 20,
                            EstimatedUnitPrice = 15.99,
                            IsCustom = false,
                            Name = "Fish",
                            Type = 8,
                            Unit = 1
                        },
                        new
                        {
                            Id = 21,
                            EstimatedUnitPrice = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Butter",
                            Type = 3,
                            Unit = 1
                        },
                        new
                        {
                            Id = 22,
                            EstimatedUnitPrice = 1.0,
                            IsCustom = false,
                            Name = "Basil",
                            Type = 0,
                            Unit = 4
                        },
                        new
                        {
                            Id = 23,
                            EstimatedUnitPrice = 0.40000000000000002,
                            IsCustom = false,
                            Name = "Cheddar Cheese",
                            Type = 6,
                            Unit = 1
                        },
                        new
                        {
                            Id = 24,
                            EstimatedUnitPrice = 3.0,
                            IsCustom = false,
                            Name = "Asparagus",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 25,
                            EstimatedUnitPrice = 1.5,
                            IsCustom = false,
                            Name = "Red Cabbage",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 26,
                            EstimatedUnitPrice = 0.75,
                            IsCustom = false,
                            Name = "Leek",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 27,
                            EstimatedUnitPrice = 0.5,
                            IsCustom = false,
                            Name = "Hazelnut",
                            Type = 10,
                            Unit = 1
                        },
                        new
                        {
                            Id = 28,
                            EstimatedUnitPrice = 0.75,
                            IsCustom = false,
                            Name = "Zucchini",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 29,
                            EstimatedUnitPrice = 0.59999999999999998,
                            IsCustom = false,
                            Name = "Grapes",
                            Type = 7,
                            Unit = 1
                        },
                        new
                        {
                            Id = 30,
                            EstimatedUnitPrice = 1.0,
                            IsCustom = false,
                            Name = "Almond",
                            Type = 10,
                            Unit = 1
                        },
                        new
                        {
                            Id = 31,
                            EstimatedUnitPrice = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Red Lentils",
                            Type = 5,
                            Unit = 1
                        },
                        new
                        {
                            Id = 32,
                            EstimatedUnitPrice = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Beans",
                            Type = 5,
                            Unit = 1
                        },
                        new
                        {
                            Id = 33,
                            EstimatedUnitPrice = 2.0,
                            IsCustom = false,
                            Name = "Chestnut",
                            Type = 10,
                            Unit = 1
                        },
                        new
                        {
                            Id = 34,
                            EstimatedUnitPrice = 0.80000000000000004,
                            IsCustom = false,
                            Name = "Apple",
                            Type = 7,
                            Unit = 0
                        },
                        new
                        {
                            Id = 35,
                            EstimatedUnitPrice = 0.59999999999999998,
                            IsCustom = false,
                            Name = "Mushroom",
                            Type = 0,
                            Unit = 1
                        },
                        new
                        {
                            Id = 36,
                            EstimatedUnitPrice = 2.0,
                            IsCustom = false,
                            Name = "Cauliflower",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 37,
                            EstimatedUnitPrice = 1.2,
                            IsCustom = false,
                            Name = "Strawberry",
                            Type = 7,
                            Unit = 1
                        },
                        new
                        {
                            Id = 38,
                            EstimatedUnitPrice = 0.40000000000000002,
                            IsCustom = false,
                            Name = "Dried Plum",
                            Type = 7,
                            Unit = 1
                        },
                        new
                        {
                            Id = 39,
                            EstimatedUnitPrice = 0.050000000000000003,
                            IsCustom = false,
                            Name = "Bread",
                            Type = 9,
                            Unit = 1
                        },
                        new
                        {
                            Id = 40,
                            EstimatedUnitPrice = 1.5,
                            IsCustom = false,
                            Name = "Red Cabbage",
                            Type = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 41,
                            EstimatedUnitPrice = 0.5,
                            IsCustom = false,
                            Name = "Hazelnut",
                            Type = 10,
                            Unit = 1
                        },
                        new
                        {
                            Id = 42,
                            EstimatedUnitPrice = 0.59999999999999998,
                            IsCustom = false,
                            Name = "Pumpkin Seeds",
                            Type = 10,
                            Unit = 1
                        },
                        new
                        {
                            Id = 43,
                            EstimatedUnitPrice = 0.5,
                            IsCustom = false,
                            Name = "Lemon",
                            Type = 7,
                            Unit = 0
                        },
                        new
                        {
                            Id = 44,
                            EstimatedUnitPrice = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Garlic",
                            Type = 0,
                            Unit = 3
                        },
                        new
                        {
                            Id = 45,
                            EstimatedUnitPrice = 1.0,
                            IsCustom = false,
                            Name = "Basil",
                            Type = 0,
                            Unit = 4
                        },
                        new
                        {
                            Id = 46,
                            EstimatedUnitPrice = 0.69999999999999996,
                            IsCustom = false,
                            Name = "Olive",
                            Type = 7,
                            Unit = 1
                        },
                        new
                        {
                            Id = 47,
                            EstimatedUnitPrice = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Rice",
                            Type = 4,
                            Unit = 1
                        },
                        new
                        {
                            Id = 48,
                            EstimatedUnitPrice = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Kidney Beans",
                            Type = 5,
                            Unit = 1
                        },
                        new
                        {
                            Id = 49,
                            EstimatedUnitPrice = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Coffee",
                            Type = 11,
                            Unit = 1
                        },
                        new
                        {
                            Id = 50,
                            EstimatedUnitPrice = 0.050000000000000003,
                            IsCustom = false,
                            Name = "Tea",
                            Type = 11,
                            Unit = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
